root_dir: ${oc.env:PROJECT_ROOT}
work_dir: ${hydra:runtime.cwd}
output_dir: ${hydra:runtime.output_dir}
dataset_path: ${paths.root_dir}/data
background_path: ${paths.root_dir}/data/background_noise/dcase18_unpacked_wav
log_dir: ${paths.output_dir}/logs/

