model_name: "eat"
model:
  _target_: src.modules.models.eat_soundnet.SoundNet
  nf: 32
  seq_len: 110250
  embed_dim: 128
  n_layers: 4
  nhead: 8
  factors: [4, 4, 4, 4]
  n_classes: ${datamodule.dataset.n_classes}
  dim_feedforward: 512
torch_compile: False
model_type: 'waveform'
sampling_rate: 22050